home/urls.py
from  . import views
from django.urls import path


app_name = 'home'
urlpatterns = [
    
    
    path('', views.Home.as_view(), name='home'),
    path('button', views.Button.as_view(), name='button'),
    path('card', views.Card.as_view(), name='card'),
    path('color', views.Color.as_view(), name='color'),
    path('border', views.Border.as_view(), name='border'),
    path('animation', views.Animation.as_view(), name='animation'),
    path('other', views.Other.as_view(), name='other'),
    path('chart', views.Chart.as_view(), name='chart'),



    path('contact_list', views.ContactList.as_view(), name='contact_list'),
    path('contact_detail/<int:pk>', views.ContactDetail.as_view(), name='contact_detail'),
    path('contact_create', views.ContactCreate.as_view(), name='contact_create'),
    path('contact_update/<int:pk>', views.ContactUpdate.as_view(), name='contact_update'),
    path('contact_delete/<int:pk>', views.ContactDelete.as_view(), name='contact_delete'),


    # path('comingsoon', views.ComingSoon.as_view(), name='comingsoon'),
    # path('service', views.Service.as_view(), name='service'),
    # path('contact', views.Contact.as_view(), name='contact'),
    # path('career', views.Career.as_view(), name='career'),
    # path('mytest', views.MyTest.as_view(), name='mytest'),
    # path('sugar/<int:cat_id>/', views.Sugar.as_view(), name='sugar'),
    # path('privacy_policy', views.PrivacyPolicy.as_view(), name='privacy_policy'),
    # path('terms', views.Terms.as_view(), name='terms'),
    # path('success_sent', views.SuccessSent.as_view(), name='success_sent'),
   
]

home/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import FileExtensionValidator

# mylifebusy.com DB

class Contact(models.Model):
    full_name = models.CharField(max_length = 50)
    position = models.CharField(max_length = 50)
    office = models.CharField(max_length = 50)
    salary = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)


    def __str__(self):
        return self.full_name
    
    class Meta:
        verbose_name = "contact"
        verbose_name_plural = "contacts"









# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=40)
    thumbnail_url = models.CharField(max_length=400)
    icon = models.CharField(max_length=100)
    active = models.BooleanField(default=False)
    
    

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'


class Icon(models.Model):
    title = models.CharField(max_length=40)
    icon_tag = models.CharField(max_length=100)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = 'icon'
        verbose_name_plural = 'icons'


class SubCategory(models.Model):
    title = models.CharField(max_length=100)
    icon = models.ForeignKey(Icon, on_delete=models.CASCADE)
    categories = models.ForeignKey(Category, on_delete=models.CASCADE,related_name='subcategory')
    price = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
    thumbnail_url = models.CharField(max_length=400)
    book_count = models.IntegerField(default = 0)
    created_date = models.DateTimeField(default=timezone.now)
    booked_date = models.DateTimeField(blank=True, null=True)
    active = models.BooleanField(default=True)
    
    

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = 'subcategory'
        verbose_name_plural = 'subcategories'


class CareerMail(models.Model):
    full_name = models.CharField(max_length=200)
    email =     models.EmailField(max_length=200) 
    phone = models.CharField(max_length=20)
    looking_for = models.CharField(max_length=200)
    document = models.FileField(upload_to='documents/',
                                validators=[FileExtensionValidator(allowed_extensions=['pdf'])])
    reference = models.CharField(max_length=300)
    def __str__(self):
        return self.email  

home/forms.py
from django import forms
from .models import CareerMail, Contact

class ContactForm(forms.ModelForm):

    class Meta: 
        model = Contact
        fields = '__all__'
        widgets = {
           'full_name' : forms.TextInput(attrs={'class':'form-control',  'required':'required',}),
            'position' : forms.TextInput(attrs={'class':'form-control',  'required':'required',}),
            'office' : forms.TextInput(attrs={'class':'form-control',  'required':'required',}),
            'salary' : forms.TextInput(attrs={'class':'form-control',  'required':'required',}),
           }
        # label = {
		# 'full_name':'Full name'
	    # }
    


class CareerMailForm(forms.ModelForm):
    full_name = forms.CharField(widget=forms.TextInput(attrs={'id':'contact-name','name' :'contact-name', 'required':'required'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'id':'contact-email','name':'contact-email',  'class':'m-required m-email','required':'required'}))
    phone = forms.CharField( required=False, widget=forms.TextInput(attrs={'id':'contact-phone','name' : 'contact-phone'}))
    looking_for = forms.CharField(required=False, widget=forms.TextInput(attrs={'id':'contact-subject', 'name':'contact-subject'}))
    document = forms.FileField(widget=forms.FileInput(attrs={'accept':'application/pdf'}))
    reference = forms.CharField(widget=forms.Textarea(attrs={'id':'contact-message', 'name':'contact-message', 'required':'required'}))

    class Meta:
        model = CareerMail
        fields = ('full_name','email','phone','looking_for','document', 'reference')
    
    
   
    

   


    
    
    
   

    


    

  
   

home/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView,View
import random
from home.models import Category,SubCategory, Contact
from . forms import CareerMailForm, ContactForm
from django.views.generic.edit import FormView
from django.http import HttpResponseRedirect, HttpResponse
from django.core.mail import send_mail, EmailMessage
from django.conf import settings
from django.contrib import messages
from pip._vendor import requests
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView 
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django import forms



# Create your views here.

class Home(LoginRequiredMixin, TemplateView):
	template_name = 'home/home.html'


class Button(LoginRequiredMixin, TemplateView):
	template_name = 'home/button.html'

class Card(LoginRequiredMixin, TemplateView):
	template_name = 'home/card.html'

class Color(LoginRequiredMixin, TemplateView):
	template_name = 'home/color.html'


class Border(LoginRequiredMixin, TemplateView):
	template_name = 'home/border.html'


class Animation(LoginRequiredMixin, TemplateView):
	template_name = 'home/animation.html'


class Other(LoginRequiredMixin, TemplateView):
	template_name = 'home/other.html'	



class Chart(LoginRequiredMixin, TemplateView):
	template_name = 'home/chart.html'	




class ContactList(ListView): 
	template_name = "home/contact.html"
	model = Contact
	

class ContactDetail(DetailView): 
    model = Contact


class ContactCreate(CreateView):
	model = Contact
	form_class = ContactForm
	success_url = reverse_lazy('home:contact_list')
	template_name = "home/contact_create.html"
	context_object_name = 'contact'


class ContactUpdate(UpdateView):
	model = Contact
	form_class = ContactForm
	success_url = reverse_lazy('home:contact_list')
	template_name = "home/contact_update.html"
	context_object_name = 'contact'
	# fields = (	'full_name',
	# 			'position',
	# 			'office',
	# 			'salary')


	# widgets = {
	# 		'full_name' : forms.TextInput(attrs={'id':'bozbash','class':'form-control', 'placeholder':'Enter movie name', 'required':'required'}),
			
	# 	}
	# label = {
	# 	'full:name':'hechne'
	# }
	

	


class ContactDelete(DeleteView):
	model = Contact
	form_class = ContactForm
	success_url = reverse_lazy('home:contact_list')
	template_name = "home/contact_delete.html"
	context_object_name = 'contact'
    




# class Table(LoginRequiredMixin, ListView):
# 	model = Person
# 	template_name = 'home/table.html'


	# def get(self, request, *args, **kwargs):
	# 	qs = Person.objects.all().values('full_name','position','office','age','start_date', 'salary')\
	# 	.filter().order_by('id')
	# 	context = {
	# 		'qs': 	qs,
	# 	}
	# 	return render(request, self.template_name, context)	



			# end of mylifebusy views #
# -----------------------------------------------#


class Sugar(View):
	template_name = 'home/sugar.html'

	def get(self, request, *args, **kwargs):
		cat_id = kwargs['cat_id']
		
		qs_subcats = SubCategory.objects.all().values('title','price','categories__title').filter(categories=cat_id)
		# if ther is no any sub cat we must avoid 
		# to send ampty dic to the templa cause it gives us error
		if(qs_subcats):
			cat = qs_subcats[0]['categories__title']
			context = {
				'menu':			"servicemenu",	
				'qs_subcats': 	qs_subcats,
				'cat': cat
			}
		else :
			context = {
				'menu':			"servicemenu",
				'cat': "There is no any sub cat"
			}

		
		
		return render(request, self.template_name, context)	


		

class Service(TemplateView):
	template_name = 'home/service.html'
	
	def get(self, request, *args, **kwargs):
		qs = SubCategory.objects.all().values('title','price','categories__id','categories__title','icon__icon_tag').filter(categories__active=True).order_by('categories__id')
		context = {
			'menu':			"servicemenu",	
			'qs': 	qs,
			
		}
		return render(request, self.template_name, context)	


class Contact(FormView):
	template_name = 'home/contact.html'
	form_class = ContactForm
	success_url = 'success_sent'


	def get_context_data(self, *args, **kwargs):
		context = super(Contact, self).get_context_data(*args, **kwargs)
		context["menu"] = 'contactmenu'
		return context
	
	def post(self, request, *args, **kwargs):
		form_class = self.get_form_class()
		form = self.get_form(form_class)

		''' Begin reCAPTCHA validation '''
		recaptcha_response = request.POST.get('g-recaptcha-response')
		data = {
			'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
			'response': recaptcha_response
		}
		r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
		result = r.json()
		verify = result["success"]
		''' End reCAPTCHA validation '''
		
		if form.is_valid():
			if verify:
				return self.form_valid(form, **kwargs)
			else: 
				messages.warning(request, 'Please correct the reCAPTCHA error below.')
				return self.form_invalid(form, **kwargs)
		else:
			
			return self.form_invalid(form, **kwargs)
	
	
	
	def form_valid(self, form):
		name = form.cleaned_data['name']
		phone = form.cleaned_data['phone']
		email = form.cleaned_data['email']
		subject = form.cleaned_data['subject']
		message =form.cleaned_data['message']
		message = 'Name: ' + name + '\n' + 'Phone: ' + phone + '\n' + 'Email: ' + email + '\n' + message
		email_from = settings.EMAIL_HOST_USER
		recipient_list = ['info@mylifebusy.com',]
		send_mail( subject, message, email_from, recipient_list )
		return super(Contact, self).form_valid(form)

	def form_invalid(self, form, **kwargs):
		context = self.get_context_data(**kwargs)
		context['form'] = form
		return self.render_to_response(context)

		


class ComingSoon(TemplateView):
	template_name = 'home/comingsoon.html'
	
	def get_context_data(self, **kwargs):
		context = super(ComingSoon, self).get_context_data(**kwargs)
		context['menu'] = "comingsoonmenu"
		return context
	

class PrivacyPolicy(TemplateView):
	template_name = 'home/privacy_policy.html'

class Terms(TemplateView):
	template_name = 'home/terms.html'

class SuccessSent(TemplateView):
	template_name = 'home/success_sent.html'

class Career(TemplateView):
	template_name = 'home/career.html'
	form_class = CareerMailForm
	
	def get(self, request, *args, **kwargs):
		form = self.form_class()
		return render(request, self.template_name, {'menu': 'careermenu','form':form,})

	def post(self, request, *args, **kwargs):
		form = self.form_class(request.POST, request.FILES)
		
		''' Begin reCAPTCHA validation '''
		recaptcha_response = request.POST.get('g-recaptcha-response')
		data = {
			'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
			'response': recaptcha_response
		}
		r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
		result = r.json()
		verify = result["success"]
		''' End reCAPTCHA validation '''
		
		if form.is_valid():
			print('form is valid')
			if verify:
				post = form.save(commit=False)
				post.published_date = timezone.now()
				post.save()

				full_name = form.cleaned_data['full_name']
				phone = form.cleaned_data['phone']
				email = form.cleaned_data['email']
				looking_for = form.cleaned_data['looking_for']
				document = request.FILES.get('document')
				reference =form.cleaned_data['reference']
				message = 'Name: ' + full_name + '\n' + 'Phone: ' + phone + '\n' + 'Email: ' + email + '\n' + looking_for + '\n' + reference
				email_from = settings.EMAIL_HOST_USER
				recipient_list = ['info@mylifebusy.com',]
				try:
					print("try")
					mail = EmailMessage(
						'Letter name comes here',
						message,
						email_from,
						recipient_list,
					)
					mail.attach_file('media/documents/'+str(document))
					mail.send()
					return HttpResponseRedirect(reverse('home:success_sent'))
					
				except:
					messages.warning(request, 'Corrupted file or too big file size.')
					return render(request, self.template_name, {'form': form,})
			
			else: 
				messages.warning(request, 'Please correct the reCAPTCHA error below.')
				return render(request, self.template_name, {'form': form,})
			
		print('form is invalid')
		messages.warning(request, 'Posted form is invalid.')
		return render(request, self.template_name, {'form': form})


class MyTest(View):
	template_name = 'home/mytest.html'
	form_class = CareerMailForm
	success_url = 'success_sent'

	# def get_context_data(self, *args, **kwargs):
	# 	context = super(MyTest, self).get_context_data(*args, **kwargs)	
	# 	context["menu"] = 'careermenu'
	# 	return context

	def get(self, request, *args, **kwargs):
		form = self.form_class()
		return render(request, self.template_name, {'menu': 'careermenu','form':form,})

	def post(self, request, *args, **kwargs):
		
		# form_class = self.get_form_class()
		# form = self.get_form(form_class)
		form = self.form_class(request.POST, request.FILES)
		
		''' Begin reCAPTCHA validation '''
		recaptcha_response = request.POST.get('g-recaptcha-response')
		data = {
			'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
			'response': recaptcha_response
		}
		r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
		result = r.json()
		verify = result["success"]
		''' End reCAPTCHA validation '''
		
		if form.is_valid():
			print('form is valid')
			if verify:
				post = form.save(commit=False)
				post.published_date = timezone.now()
				post.save()

				full_name = form.cleaned_data['full_name']
				phone = form.cleaned_data['phone']
				email = form.cleaned_data['email']
				looking_for = form.cleaned_data['looking_for']
				document = request.FILES.get('document')
				reference =form.cleaned_data['reference']
				message = 'Name: ' + full_name + '\n' + 'Phone: ' + phone + '\n' + 'Email: ' + email + '\n' + looking_for + '\n' + reference
				email_from = settings.EMAIL_HOST_USER
				recipient_list = ['info@mylifebusy.com',]
				try:
					print("try")

templates/home/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

       <!-- Content Wrapper -->
       <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">
  
          <!-- Topbar -->
          <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
  
            <!-- Sidebar Toggle (Topbar) -->
            <form class="form-inline">
              <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                <i class="fa fa-bars"></i>
              </button>
            </form>
  
            <!-- Topbar Search -->
            <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
              <div class="input-group">
                <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                <div class="input-group-append">
                  <button class="btn btn-primary" type="button">
                    <i class="fas fa-search fa-sm"></i>
                  </button>
                </div>
              </div>
            </form>
  
            <!-- Topbar Navbar -->
            <ul class="navbar-nav ml-auto">
  
              <!-- Nav Item - Search Dropdown (Visible Only XS) -->
              <li class="nav-item dropdown no-arrow d-sm-none">
                <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-search fa-fw"></i>
                </a>
                <!-- Dropdown - Messages -->
                <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                  <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                      <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                      <div class="input-group-append">
                        <button class="btn btn-primary" type="button">
                          <i class="fas fa-search fa-sm"></i>
                        </button>
                      </div>
                    </div>
                  </form>
                </div>
              </li>
  
              <!-- Nav Item - Alerts -->
              <li class="nav-item dropdown no-arrow mx-1">
                <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-bell fa-fw"></i>
                  <!-- Counter - Alerts -->
                  <span class="badge badge-danger badge-counter">3+</span>
                </a>
                <!-- Dropdown - Alerts -->
                <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
                  <h6 class="dropdown-header">
                    Alerts Center
                  </h6>
                  <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                      <div class="icon-circle bg-primary">
                        <i class="fas fa-file-alt text-white"></i>
                      </div>
                    </div>
                    <div>
                      <div class="small text-gray-500">December 12, 2019</div>
                      <span class="font-weight-bold">A new monthly report is ready to download!</span>
                    </div>
                  </a>
                  <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                      <div class="icon-circle bg-success">
                        <i class="fas fa-donate text-white"></i>
                      </div>
                    </div>
                    <div>
                      <div class="small text-gray-500">December 7, 2019</div>
                      $290.29 has been deposited into your account!
                    </div>
                  </a>
                  <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                      <div class="icon-circle bg-warning">
                        <i class="fas fa-exclamation-triangle text-white"></i>
                      </div>
                    </div>
                    <div>
                      <div class="small text-gray-500">December 2, 2019</div>
                      Spending Alert: We've noticed unusually high spending for your account.
                    </div>
                  </a>
                  <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
                </div>
              </li>
  
              <!-- Nav Item - Messages -->
              <li class="nav-item dropdown no-arrow mx-1">
                <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-envelope fa-fw"></i>
                  <!-- Counter - Messages -->
                  <span class="badge badge-danger badge-counter">7</span>
                </a>
                <!-- Dropdown - Messages -->
                <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
                  <h6 class="dropdown-header">
                    Message Center
                  </h6>
                  <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                      <img class="rounded-circle" src="https://source.unsplash.com/fn_BT9fwg_E/60x60" alt="">
                      <div class="status-indicator bg-success"></div>
                    </div>
                    <div class="font-weight-bold">
                      <div class="text-truncate">Hi there! I am wondering if you can help me with a problem I've been having.</div>
                      <div class="small text-gray-500">Emily Fowler · 58m</div>
                    </div>
                  </a>
                  <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                      <img class="rounded-circle" src="https://source.unsplash.com/AU4VPcFN4LE/60x60" alt="">
                      <div class="status-indicator"></div>
                    </div>
                    <div>
                      <div class="text-truncate">I have the photos that you ordered last month, how would you like them sent to you?</div>
                      <div class="small text-gray-500">Jae Chun · 1d</div>
                    </div>
                  </a>
                  <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                      <img class="rounded-circle" src="https://source.unsplash.com/CS2uCrpNzJY/60x60" alt="">
                      <div class="status-indicator bg-warning"></div>
                    </div>
                    <div>
                      <div class="text-truncate">Last month's report looks great, I am very happy with the progress so far, keep up the good work!</div>
                      <div class="small text-gray-500">Morgan Alvarez · 2d</div>
                    </div>
                  </a>
                  <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                      <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60" alt="">
                      <div class="status-indicator bg-success"></div>
                    </div>
                    <div>
                      <div class="text-truncate">Am I a good boy? The reason I ask is because someone told me that people say this to all dogs, even if they aren't good...</div>
                      <div class="small text-gray-500">Chicken the Dog · 2w</div>
                    </div>
                  </a>
                  <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
                </div>
              </li>
  
              <div class="topbar-divider d-none d-sm-block"></div>
  
              <!-- Nav Item - User Information -->
              <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <span class="mr-2 d-none d-lg-inline text-gray-600 small">Valerie Luna</span>
                  <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
                </a>
                <!-- Dropdown - User Information -->
                <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                  <a class="dropdown-item" href="#">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Profile
                  </a>
                  <a class="dropdown-item" href="#">
                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                    Settings
                  </a>
                  <a class="dropdown-item" href="#">
                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                    Activity Log
                  </a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                  </a>
                </div>
              </li>
  
            </ul>
  
          </nav>
          <!-- End of Topbar -->
  
          <!-- Begin Page Content -->
          <div class="container-fluid">
  
            <!-- Page Heading -->
            <h1 class="h3 mb-2 text-gray-800">Tables</h1>
            <p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below. For more information about DataTables, please visit the <a target="_blank" href="https://datatables.net">official DataTables documentation</a>.</p>
  
            <!-- DataTales Example -->
            <div class="card shadow mb-4">
              <div class="card-header py-3">
                
                <form class="form-inline">
                    <div class="form-group">
                      
                    </div>
                  </form>
              </div>
              
              <div class="card-body">
                <div class="table-responsive">
                    
                  <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                      <tr>
                        
                        <th>Name</th>
                        <th>Position</th>
                        <th>Office</th>
                        <th>Salary</th>
                        <th></th>
                      </tr>
                    </thead>
                    
                    <tbody>
                      {% for item in object_list%}
                      <tr>
                        
                        <td>{{item.full_name}}</td>
                        <td>{{item.position}}</td>
                        <td>{{item.office}}</td>
                        <td>{{item.salary}}</td>
                        <td style="text-align: center;">
                          <a  href="{% url 'home:contact_update'  pk=item.id  %}">edit</a> |
                          <a  href="{% url 'home:contact_delete'  pk=item.id  %}">delete</a>
                          </td>
                      </tr>
                      {% endfor%}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
           <div  style="float: right;">
            <a  type="button" class="form-control" href="{% url 'home:contact_create'%}">Add Contact</a>
            <br>
          </div>   
          </div>
          <!-- /.container-fluid -->
  
        </div>
        <!-- End of Main Content -->
  
        <!-- Footer -->
        <footer class="sticky-footer bg-white">
          <div class="container my-auto">
            <div class="copyright text-center my-auto">
              <span>Copyright &copy; Your Website 2020</span>
            </div>
          </div>
        </footer>
        <!-- End of Footer -->
  
      </div>
      <!-- End of Content Wrapper -->
{% endblock %}